---
title: Digital Pebble
timezone: UTC
collections:
  references:
    title: References
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: references
  values:
    main-description: 
    title: 
    image: 
    image-alt:
    sitemap: false
email: contact@digitalpebble.com
meta-description: DigitalPebble can help your organisation by advising on best practice and identifying suitable resources, 
  designing scalable solutions as well as implementing them. We can help you deploy and monitor your project on your premises or on the cloud.
baseurl: 
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
permalink: "/blog/:title"
theme: minima
exclude:
- Gemfile.lock
- node_modules
plugins:
- jekyll-feed
- jekyll-seo-tag
