---
title: Digital Pebble
timezone: UTC
collections:
  references:
    title: References
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: references
  values:
    main-description: 
    title: 
    image: 
    image-alt:
    sitemap: false
email: contact@digitalpebble.com
meta-description:  DigitalPebble Ltd is a consultancy specialised in green software, greenops and finops.
baseurl: 
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
permalink: "/blog/:title"
theme: minima
exclude:
- Gemfile.lock
- node_modules
plugins:
- jekyll-feed
- jekyll-seo-tag
