# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DigitalPebble
email: contact@digitalpebble.com
description: DigitalPebble Ltd is a consultancy specialised in web crawling, natural language processing, information retrieval and extraction. Our expertise is based on open source solutions, such as Nutch, Gate or SOLR.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://digitalpebble.com" # the base hostname & protocol for your site
twitter_username: digitalpebble
github_username:  digitalpebble

# Build settings
markdown: kramdown
